[project]
name = "pyalgolab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8.4.2"]

[tool.pytest.ini_options]
pythonpath = ["src"]